language: cpp

branches:
  only:
    - develop

notifications:
  email:
    recipients:
      - grafikrobot@gmail.com
    on_success: change
    on_failure: change
  irc:
    channels:
      - "chat.freenode.net#boost"
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
    on_success: change
    on_failure: change

os:
  - linux

matrix:
  include:
    #- compiler: clang
    #  env: TOOLSET=clang-3.4
    #- compiler: clang
    #  env: TOOLSET=clang-3.5
    #- compiler: gcc
    #  env: TOOLSET=gcc-4.7
    #- compiler: gcc
    #  env: TOOLSET=gcc-4.8
    - compiler: gcc
      env: TOOLSET=gcc-4.9

before_install: wget "https://raw.githubusercontent.com/boostorg/regression/develop/ci/src/script.py"
install: python script.py travis_install
before_script: python script.py travis_before_script
script: python script.py travis_script
after_success: python script.py travis_after_success
after_failure: python script.py travis_after_failure
after_script: python script.py travis_after_script
