language: cpp

compiler:
  - gcc
  - clang

install:
  - wget "https://github.com/boostorg/build/archive/develop.tar.gz"
  - tar -xzvf develop.tar.gz
  - cd build-develop
  - ./bootstrap.sh
  - sudo ./b2 install --prefix=/usr
  - cd $TRAVIS_BUILD_DIR

before_script:
  - cd $TRAVIS_BUILD_DIR
  - 'echo "project ROOT : : : build-dir bin ;" > jamroot.jam'

script:
  - cd $TRAVIS_BUILD_DIR
  - cd test && b2 -a --verbose-test

branches:
  only:
    - develop

notifications:
  email:
    - grafikrobot@gmail.com
  irc:
    channels:
      - "chat.freenode.net#boost"
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
    on_success: change
    on_failure: change

os:
  - linux
